language: rust
rust:
  - stable
  - beta
  - nightly
install:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
  - cargo fmt
  - cargo clippy
  - cargo test
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true